# version: "3.9"

services:

  # --- BACKEND DJANGO ---
  backend:

    image: ghcr.io/aka056/projet-devops/backend:latest # en production plutot au lieu de build On utilise l'image construite et poussée sur GitHub Container Registry
    container_name: backend-prod # Nom du conteneur 
    env_file: # On charge les variables d'environnement depuis le fichier .env.prod
      - ./backend/.env.prod
    expose: # ici on expose le port 8000 au lieu de le mapper directement pour des raisons de sécurité car on ne veut pas exposer le backend directement à l'extérieur
      - "8000"
    depends_on:  # On s'assure que le service db est démarré avant le backend
      - db
    networks:
      - app-net
    # La commande à exécuter pour démarrer le serveur Django avec Gunicorn aulieu de runserver car gunicorn est plus adapté pour la production 
    command: > 
      sh -c "python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000" 

  # --- FRONTEND REACT / NEXT.JS ---
  frontend:
    image: ghcr.io/aka056/projet-devops/frontend:latest # en production plutot au lieu de build On utilise l'image construite et poussée sur GitHub Container Registry
    container_name: frontend-prod # Nom du conteneur
    expose: # On expose le port 3000 pour la communication entre conteneurs
      - "3000" 
    depends_on: # On s'assure que le service backend est démarré avant le frontend
      - backend 
    environment:
    - NODE_ENV=production
    networks:
      - app-net
    env_file: # On charge les variables d'environnement depuis le fichier .env.prod
      - ./frontend/.env.prod
    # La commande à exécuter pour démarrer le serveur de production Next.js
    command: ["npm", "run", "start"]


  # --- BASE DE DONNÉES POSTGRES ---
  db: 
    image: postgres:15 
    container_name: db-prod # Nom du conteneur
    env_file:
      - ./backend/.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data # On monte un volume pour persister les données de la base de données
    networks:
      - app-net



# Déclaration des volumes
volumes:
  postgres_data: 

# Déclaration des réseaux
networks:
  app-net: