name: Deploy to Production (AWS EC2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️ recuperer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️ Générer les fichiers .env.prod depuis GitHub Secrets
      - name: Generate backend .env.prod
        run: |
          echo "APP_ENV=prod" >> backend/.env.prod
          echo "DEBUG=False" >> backend/.env.prod
          echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> backend/.env.prod

          echo "DATABASE_NAME=${{ secrets.DB_NAME }}" >> backend/.env.prod
          echo "DATABASE_USER=${{ secrets.DB_USER }}" >> backend/.env.prod
          echo "DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/.env.prod
          echo "DATABASE_HOST=db" >> backend/.env.prod
          echo "DATABASE_PORT=5432" >> backend/.env.prod

      - name: Generate frontend .env.prod
        run: |
          echo "APP_ENV=prod" >> frontend/.env.prod
          echo "NEXT_PUBLIC_API_URL=${{ secrets.FRONT_PUBLIC_URL }}" >> frontend/.env.prod
          echo "INTERNAL_API_URL=http://backend:8000/" >> frontend/.env.prod
      
      - name: genererate db .env file
        run: |
          echo "POSTGRES_DB=${{ secrets.DB_NAME }}" >> backend/.env.db
          echo "POSTGRES_USER=${{ secrets.DB_USER }}" >> backend/.env.db
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/.env.db

      # 3 Se connecter en SSH à EC2
      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
          script: |
            set -e
            
            cd /var/www/Projet-DevOps-ready

            echo " Pulling latest code..."
            git pull origin main

            echo " Updating .env.prod files..."
            cp backend/.env.prod ./backend/.env.prod
            cp frontend/.env.prod ./frontend/.env.prod

            echo " Stopping old containers..."
            docker compose -f docker-compose.prod.yml down || true

            echo " Rebuilding images..."
            docker compose -f docker-compose.prod.yml build

            echo " Starting services..."
            docker compose -f docker-compose.prod.yml up -d

            echo " Deployment completed!"

      - name: Show logs if failure
        if: failure()
        run: docker compose -f docker-compose.prod.yml logs --tail=200

